###

PATCH {{WebApi_HostAddress}}/api/v1/admin/quizzes/1
Content-Type: application/json-patch+json

[
  {
    "op": "add",
    "path": "/items/-",
    "value": {
      "question": "4*7",
      "correctAnswer": "28",
      "incorrectAnswers": ["26","27","29"]
    }
  }
]

###

POST  https://localhost:7196/api/v1/quizzes/1/items/1/answer
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoia2Fyb2wiLCJnZW5kZXIiOiJtYWxlIiwiZW1haWwiOiJrYXJvbEB3c2VpLmVkdS5wbCIsImV4cCI6MTcxMzkwMDM2OSwianRpIjoiM2ZjZTRiMGYtNWUyNy00NGQ5LWE2MjgtN2RkNjE5YzZlMzhlIiwiYXVkIjoid3NlaSIsImlzcyI6IndzZWkifQ.kbd2jAkeYCHldngWb8LBAuVQ1ULaJBrKGZ1nbDNZNL8

{
  "userId": 1,
  "answer": "5"
}